spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/usinsa?currentSchema=public
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

security:
  jwt:
    issuer: "usinsa-api"
    access:
      secret: +draywRdxn8JZR57W2nLftO+Cl01NQQCUGieppbS
      expiration: 900s
    refresh:
      secret: +draywRdxn8JZR57W2nLftO+Cl01NQQCUGieppbS
      expiration: 14d