spring:
  profiles:
    active: dev   # 기본 active → 개발 환경
    group:
      dev:
        - secret
      prod:
        - secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    serialization:
      indent-output: true

logging:
  level:
    root: INFO
