security:
  jwt:
    issuer: "usinsa-api"
    access:
      secret: ${JWT_ACCESS_SECRET}
      expiration: 900s   # 15분
      refresh:
        secret: ${JWT_REFRESH_SECRET}
        expiration: 14d    # 14일

spring:
  application:
    name: usinsa-be

  config:
    import: "optional:classpath:application-secret.yaml"

  profiles:
    group:
      local: local
      dev: dev
      prod: prod
    active: local

  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        default_batch_fetch_size: 100
    show-sql: false
    hibernate:
      ddl-auto: none

server:
  port: 8080

logging:
  level:
    root: INFO
