/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RefreshReq: {
            refreshToken?: string;
        };
        ErrorDetail: {
            code?: string;
            message?: string;
        };
        RsDataTokenPair: {
            success?: boolean;
            /** Format: int32 */
            status?: number;
            error?: components["schemas"]["ErrorDetail"];
            data?: components["schemas"]["TokenPair"];
        };
        TokenPair: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: int64 */
            accessExpEpochSec?: number;
            /** Format: int64 */
            refreshExpEpochSec?: number;
        };
        RsDataVoid: {
            success?: boolean;
            /** Format: int32 */
            status?: number;
            error?: components["schemas"]["ErrorDetail"];
            data?: Record<string, never>;
        };
        LoginReq: {
            email?: string;
            password?: string;
        };
        LoginRes: {
            /** Format: int64 */
            memberId?: number;
            email?: string;
            name?: string;
            nickname?: string;
            accessToken?: string;
            refreshToken?: string;
            /** Format: int64 */
            accessTokenExp?: number;
            /** Format: int64 */
            refreshTokenExp?: number;
        };
        RsDataLoginRes: {
            success?: boolean;
            /** Format: int32 */
            status?: number;
            error?: components["schemas"]["ErrorDetail"];
            data?: components["schemas"]["LoginRes"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataTokenPair"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataLoginRes"];
                };
            };
        };
    };
}
